### ISSUE TITLE
Расскажи про работу бота пожалуйста.

### ISSUE THREAD

**Issue by WSCHUDO** [a-badalyan/torgi-gov-telegram-bot#15]
Развернул твой проект в докере. Выбрал регион и категорию, и дальше тишина, терминал показывает что происходят какие-то пуши, но до меня они почему-то не доходят. Ключ бота заменил. 

Расскажи пожалуйста, что я сделал не так?)

**Comment by WSCHUDO** [comment]
И ещё такая ошибка выдаётся 

`torgi-gov-telegram-bot-main-1   | 
torgi-gov-telegram-bot-main-1   | > torgi-gov-telegram-bot@1.0.0 start
torgi-gov-telegram-bot-main-1   | > node index.js
torgi-gov-telegram-bot-main-1   | 
torgi-gov-telegram-bot-main-1   | node:internal/modules/cjs/loader:1031
torgi-gov-telegram-bot-main-1   |   throw err;
torgi-gov-telegram-bot-main-1   |   ^
torgi-gov-telegram-bot-main-1   | 
torgi-gov-telegram-bot-main-1   | Error: Cannot find module 'ts-node/register/transpile-only'
torgi-gov-telegram-bot-main-1   | Require stack:
torgi-gov-telegram-bot-main-1   | - /code/index.js
torgi-gov-telegram-bot-main-1   |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
torgi-gov-telegram-bot-main-1   |     at Function.Module._load (node:internal/modules/cjs/loader:873:27)
torgi-gov-telegram-bot-main-1   |     at Module.require (node:internal/modules/cjs/loader:1100:19)
torgi-gov-telegram-bot-main-1   |     at require (node:internal/modules/cjs/helpers:108:18)
torgi-gov-telegram-bot-main-1   |     at Object.<anonymous> (/code/index.js:1:1)
torgi-gov-telegram-bot-main-1   |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
torgi-gov-telegram-bot-main-1   |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
torgi-gov-telegram-bot-main-1   |     at Module.load (node:internal/modules/cjs/loader:1076:32)
torgi-gov-telegram-bot-main-1   |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
torgi-gov-telegram-bot-main-1   |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
torgi-gov-telegram-bot-main-1   |   code: 'MODULE_NOT_FOUND',
torgi-gov-telegram-bot-main-1   |   requireStack: [ '/code/index.js' ]
torgi-gov-telegram-bot-main-1   | }
torgi-gov-telegram-bot-main-1 exited with code 1`

**Comment by WSCHUDO** [comment]
И ещё вылезла такая ошибка;(

2023-07-06 23:04:29 
2023-07-06 23:04:29 > torgi-gov-telegram-bot@1.0.0 start
2023-07-06 23:04:29 > node index.js
2023-07-06 23:04:29 
2023-07-06 23:04:29 node:internal/modules/cjs/loader:1031
2023-07-06 23:04:29   throw err;
2023-07-06 23:04:29   ^
2023-07-06 23:04:29 
2023-07-06 23:04:29 Error: Cannot find module 'ts-node/register/transpile-only'
2023-07-06 23:04:29 Require stack:
2023-07-06 23:04:29 - /code/index.js
2023-07-06 23:04:29     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
2023-07-06 23:04:29     at Function.Module._load (node:internal/modules/cjs/loader:873:27)
2023-07-06 23:04:29     at Module.require (node:internal/modules/cjs/loader:1100:19)
2023-07-06 23:04:29     at require (node:internal/modules/cjs/helpers:108:18)
2023-07-06 23:04:29     at Object.<anonymous> (/code/index.js:1:1)
2023-07-06 23:04:29     at Module._compile (node:internal/modules/cjs/loader:1198:14)
2023-07-06 23:04:29     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
2023-07-06 23:04:29     at Module.load (node:internal/modules/cjs/loader:1076:32)
2023-07-06 23:04:29     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
2023-07-06 23:04:29     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
2023-07-06 23:04:29   code: 'MODULE_NOT_FOUND',
2023-07-06 23:04:29   requireStack: [ '/code/index.js' ]
2023-07-06 23:04:29 }
2023-07-06 23:04:53 
2023-07-06 23:04:53 > torgi-gov-telegram-bot@1.0.0 start
2023-07-06 23:04:53 > node index.js
2023-07-06 23:04:53 
2023-07-06 23:04:53 node:internal/modules/cjs/loader:1031
2023-07-06 23:04:53   throw err;
2023-07-06 23:04:53   ^
2023-07-06 23:04:53 
2023-07-06 23:04:53 Error: Cannot find module 'ts-node/register/transpile-only'
2023-07-06 23:04:53 Require stack:
2023-07-06 23:04:53 - /code/index.js
2023-07-06 23:04:53     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
2023-07-06 23:04:53     at Function.Module._load (node:internal/modules/cjs/loader:873:27)
2023-07-06 23:04:53     at Module.require (node:internal/modules/cjs/loader:1100:19)
2023-07-06 23:04:53     at require (node:internal/modules/cjs/helpers:108:18)
2023-07-06 23:04:53     at Object.<anonymous> (/code/index.js:1:1)
2023-07-06 23:04:53     at Module._compile (node:internal/modules/cjs/loader:1198:14)
2023-07-06 23:04:53     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
2023-07-06 23:04:53     at Module.load (node:internal/modules/cjs/loader:1076:32)
2023-07-06 23:04:53     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
2023-07-06 23:04:53     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
2023-07-06 23:04:53   code: 'MODULE_NOT_FOUND',
2023-07-06 23:04:53   requireStack: [ '/code/index.js' ]
2023-07-06 23:04:53 }

**Comment by WSCHUDO** [comment]
И коннект с базой данных происходит по дефолтным log и pass? 

MONGO_URI: mongodb://root:example@mongo:27017/

**Comment by WSCHUDO** [comment]
Артём, выйди на связь плиз) Очень нужна твоя помощь 🙏  моя телега wschudo

**Comment by a-badalyan** [comment]
Здравствуйте.
Пофиксил запрос в базу.
Бот находится на стадии разработки, могут встречаться баги )

Локальный запуск через docker-compose up, затем необходимо перейти в телеграм, выполнить команду /set_region, выбрать регион, выполнить команду /set_notice_type и выбрать тип торгов.

В будущем обязательно напишу документацию.

Больше спасибо за проявленное внимание )
